# Generated by Django 4.1 on 2023-11-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_del_area', models.CharField(max_length=150)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=75)),
                ('Edad', models.IntegerField()),
                ('DUI', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=75)),
                ('Edad', models.IntegerField()),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppS17.area')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_venta', models.DateField()),
                ('Monto', models.FloatField()),
                ('ClienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppS17.cliente')),
                ('EmpleadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppS17.empleado')),
            ],
        ),
    ]
